apiVersion: v1
kind: Service
metadata:
  name: {{ include "dclaw-app.fullname" . }}-backend
  labels:
    app: {{ include "dclaw-app.name" . }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8095
      protocol: TCP
      name: http
  selector:
    app: {{ include "dclaw-app.name" . }}
    component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dclaw-app.fullname" . }}-frontend
  labels:
    app: {{ include "dclaw-app.name" . }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: {{ include "dclaw-app.name" . }}
    component: frontend
